dudu.write('蜡笔小新', 300,
	're mi_ so si_ re 0~',
	'mi so_ la do+_ mi 0~',
	'si do+_ si do+_ si so_ si la:3 0:3.5',
	're mi_ so si_ re 0~',
	'mi so_ la do+_ mi 0~',
	'si do+_ si do+_ si so_ la so:3 0:3.5'
);
dudu.write('超级马里奥', 300,
	'la_ la_ 0_ la_ 0_ fa_ la_ 0_ do+_ 0. do_ 0.'
);
dudu.write('突然好想你', 600,
	'0_ so-_ mi mi_ do_ re_ do_ si-_ do:2.25 0.',
	'do_ fa fa_ mi_ fa_ mi_ fa= so:.75 re~ 0_',
	'do_ si-_ do= la:1.25 la_ si= re+:.75',
		'do+_ si= la_ so:1.25 so= la_ mi= mi_',
	'do_ si-_ do= so:1.25 0:.75 so= so_ fa_ la-_ si-_ do~ 0',
	'la_ si_ do+ mi+ re+ do+_ re+_ so re+ do+',
	'la_ si_ do+ mi+ re+ do+ mi+~ 0',
	'la_ si_ do+ mi+ re+ so+_ re+_ fa+_ mi+= re+_ mi+_ re+= do+:.75',
	'la_ si_ do+ mi+ re+ do+ do+:3'
);
dudu.write('好累', 800,
	'0 0 0 0 0 so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 0_ so_ so#_ mi_ re_ mi_',
	're_^ do. 0_ do_ do_ si-_ la-#:3 0_ do_',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re=',
	'mi_ fa_ re_ mi_ do_ la-_ la-_ la-_',
	're 0_ mi_ fa_ re_ mi_ fa_ so_ 0_ 0 0 0',
	'0_ mi-_ la-_ si-_ do=^ si-= do si-= la-= si-_ mi-. 0 0',
	'0_ mi-_ si-_ do_ mi_ re do= si-= do_ si-_ do_ la-_^ la-~',
	'0_ si-_ si-_ do_ re_ re do=^ si-= la-=^ si-= do. 0 do_ do_',
	'si-_ fa-_ fa-_ fa-_^ fa-_ fa-_ si-_ so-=^ fa-=^ so-. 0 0',
	'0_ mi-_ la-_ si-_ la-=^ si-= do si-= la-= si-_ mi-. 0 0',
	'0_ mi-= mi-= si-_ do_ re=^ do= re do= si-= do_ si-_ do_ la-_^ la-~',
	'0_ si-= si-= si-_ do_ mi_ re_ do_ si-_ re_ la- re_ do do_ do_',
	'si-= la-= si-= 0_ si-= do= re= re= re= re= re_ fa_ mi~ 0 0_ mi-= mi-=',
	'mi= mi= mi= mi= mi 0= mi= fa= so= fa= mi= mi= re= fa= mi= mi= mi= mi 0 0_ mi-= mi-=',
	'mi= mi= mi= mi= mi mi_ fa= so= fa_ mi= re= mi_ mi= mi= mi 0 0_ la-= si-=',
	'do= do= do= do= do 0_ do= do= si-_ la-_ do re mi 0_ mi= mi=',
	're= re= re= re= re 0_ re= re= mi_ fa_ mi_ mi_ mi_ mi_ mi 0',
	'0 0 0 0 0 so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 0_ so_ so#_ mi_ re_ mi_',
	're_^ do. 0_ do_ do_ si-_ la-#:3 0_ do_',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re=',
	'mi_ fa_ re_ mi_ do_ la-_ la-_ la-_',
	're 0_ mi_ fa_ re_ mi_ fa_ so_ 0_ so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 so_ so_ so#_ mi_ si_ do+_',
	'do+:3^ do+_^ si_^ la#~^ la#_^ la_ 0_ fa= mi=',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re= mi so do+ 0_ la-= la-=',
	'mi_ fa= fa=^ fa_ la-= la-= mi_ re.^ re_ 0_ so-_ do_ fa_ mi_ re_ mi_',
	're_ do. so-_ do_ re do mi_^ re_ re_^ do_ mi_^ fa_',
	'so:4 fa la_^ so_ la_^ so_ la_^ si_',
	'do+:4 so~ so~',
	'so~ fa~ do so- do re',
	'mi~ do mi fa do_ so-_ fa fa',
	'mi do_ re_ fa_ mi_ mi_ do_ re re_ mi_ fa_ re_ mi_ fa_',
	'so so_ la_ si_ so_ la_ si_ do+ 0 0 0',
	'0 fa_ so_ fa_ so_ la_ so_ so:4',
	'0 so_ so_ so_ so_ so_ la_ la fa_ fa_ fa so_^ la_',
	'so do_ do_ do_ re_ mi_ do_ re fa_ mi_ re_ fa_ mi_ re_',
	'so_ la_ fa_ so_ la_ si_ so_ la_ si so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 0_ so_ so#_ mi_ re_ mi_',
	're_^ do.^ do~ 0 la so 0',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ do_ do_ do_ do= mi=^ mi~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ fa_ mi_ do= re_ re=^ re~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ do_ do_ do_ do= mi=^ mi~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ fa= mi= do= do= 0_ fa= mi= do= do= 0_ fa= mi= do= do=',
	'0 0'
);
dudu.write('好累啊', 800,
	'0 0 0 0 0 so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 0_ so_ so#_ mi_ re_ mi_',
	're_^ do. 0_ do_ do_ si-_ la-#:3 0_ do_',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re=',
	'mi_ fa_ re_ mi_ do_ la-_ la-_ la-_',
	're 0_ mi_ fa_ re_ mi_ fa_ so_ 0_ 0 0 0',
	'0_ mi-_ la-_ si-_ do=^ si-= do si-= la-= si-_ mi-. 0 0',
	'0_ mi-_ si-_ do_ mi_ re do= si-= do_ si-_ do_ la-_^ la-~',
	'0_ si-_ si-_ do_ re_ re do=^ si-= la-=^ si-= do. 0 do_ do_',
	'si-_ fa-_ fa-_ fa-_^ fa-_ fa-_ si-_ so-=^ fa-=^ so-. 0 0',
	'0_ mi-_ la-_ si-_ la-=^ si-= do si-= la-= si-_ mi-. 0 0',
	'0_ mi-= mi-= si-_ do_ re=^ do= re do= si-= do_ si-_ do_ la-_^ la-~',
	'0_ si-= si-= si-_ do_ mi_ re_ do_ si-_ re_ la- re_ do do_ do_',
	'si-= la-= si-= 0_ si-= do= re= re= re= re= re_ fa_ mi~ 0 0_ mi-= mi-=',
	'mi= mi= mi= mi= mi 0= mi= fa= so= fa= mi= mi= re= fa= mi= mi= mi= mi 0 0_ mi-= mi-=',
	'mi= mi= mi= mi= mi mi_ fa= so= fa_ mi= re= mi_ mi= mi= mi 0 0_ la-= si-=',
	'do= do= do= do= do 0_ do= do= si-_ la-_ do re mi 0_ mi= mi=',
	're= re= re= re= re 0_ re= re= mi_ fa_ mi_ mi_ mi_ mi_ mi 0',
	'0 0 0 0 0 so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 0_ so_ so#_ mi_ re_ mi_',
	're_^ do. 0_ do_ do_ si-_ la-#:3 0_ do_',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re=',
	'mi_ fa_ re_ mi_ do_ la-_ la-_ la-_',
	're 0_ mi_ fa_ re_ mi_ fa_ so_ 0_ so-_ do_ do_ re_ mi_ fa_',
	'so:4 0 so_ so_ so#_ mi_ si_ do+_',
	'do+:3^ do+_^ si_^ la#~^ la#_^ la_ 0_ fa= mi=',
	'so_ fa_ 0_ fa= mi= so_ fa_ 0_ mi= re= mi so do+ 0_ la-= la-=',
	'mi_ fa= fa=^ fa_ la-= la-= mi_ re.^ re_ 0_ so-_ do_ fa_ mi_ re_ mi_',
	're_ do. so-_ do_ re do mi_^ re_ re_^ do_ mi_^ fa_',
	'so si-_ si-_ si-_ so-_ si-_^ re_ fa:4',
	'0 so so so so~ so~',
	'so~ fa~ do so- do re',
	'mi~ do mi fa do_ so-_ fa fa',
	'mi do_ re_ fa_ mi_ mi_ do_ re re_ mi_ fa_ re_ mi_ fa_',
	'so so_ la_ si_ so_ la_ si_ mi mi mi mi_^ fa_',
	'so:4 so- do do do_^ re_',
	'mi:4 la fa_ fa_ fa so_^ la_',
	'so do_ do_ do_ re_ mi_ do_ re fa_ mi_ re_ fa_ mi_ re_',
	'so_ la_ fa_ so_ la_ si_ so_ la_ si so-_ do_ do_ re_ mi_ fa_',
	'0_ so-= so-= do= do= 0_ so-= la-_^ so-= do_ do_ 0_ so-= so-= do= do= 0_ si-= do_^ si-= mi_ re_',
	'0_ so-= so-= do= do= 0_ so-= la-_^ so-= do_ do_ 0 la-_ si-_ la-= la-= 0_ do= do= re_ do_',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ do_ do_ do_ do= mi=^ mi~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ fa_ mi_ do= re_ re=^ re~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ do_ do_ do_ do= mi=^ mi~',
	'mi_ so_ so_ mi= so=^ so= so_ mi= re_ do_ fa= mi= do= do= 0_ fa= mi= do= do= 0_ fa= mi= do= do=',
	'0 0'
);
